### PR TITLE
Update Donor properties. DM-384

### PR DESCRIPTION
**Pull request by kreinold**
Change hasEthnicity to hasReportedEthnicity and hasGeneticAncestry.
Capture reason for missing data in an annotation
Remove Age and Medical History
Add definition for FamilyMember
Added hasDiseaseStage and updated definitions; dateOfBirth needs to be date/time; a day is not granular enough.
To capture the strain of model organisms other than Mouse, added this is an optional property for all Donors (clearly nonsensical for Humans though).

### CODE REVIEW

**Comment by rsc3** [comment]
https://broadworkbench.atlassian.net/jira/software/projects/DM/boards/105?selectedIssue=DM-384

**Review by kreinold — COMMENTED** [review]
minor change

**Review by kreinold — COMMENTED** [review]
Updated cardinality of hasGeneticAncestry for Donor and minor changes to hasDonorAgeAtCollection.

**Review by rsc3 — CHANGES_REQUESTED** [review]
I still dont see the cardinalities for hasGeneticAncestry and hasReportedEthnicity on Human Donor.

**Pull request merged**
